Put proxy FQDN in wpad.dat for authenticated mode.
NethServer/nethserver-squid pull request #23
Opened 2018-07-30 17:04 UTC by ramiro

Fixes NethServer/dev#5555

See also https://community.nethserver.org/t/non-transparent-proxy-wpad-file-contains-ip-address-of-nethserver-server-should-be-fqdn/7093

2018-07-31 10:30 UTC, gsanchietti requested changes
The proposed solution will not work on many installation where the FQDN of the machine is not the one used by LAN clients to access the gateway itself.

It seems that we can provide multiple "PROXY" using a fail-over modules (see https://findproxyforurl.com/example-pac-file/).

I suggest to provide both configuration: first the one with the FQDN and second the one with the green IP address.

Please make sure to test both scenarios.

2018-07-31 13:48 UTC, ramiro commented
> It seems that we can provide multiple "PROXY" using a fail-over modules (see https://findproxyforurl.com/example-pac-file/).
> 

I'd say yes, this is a feature NethServer is  already using, as it can be seen in the sample `proxy.pac` file I pasted in the NethServer/dev#5555 issue.

> I suggest to provide both configuration: first the one with the FQDN and second the one with the green IP address.
> 

Could you please provide more details about this? I'm not familiar enough with NS development terminology; don't know if ypu are a member of the dev team but you seem to grasp better than me what *"provide both configurations"* means. Do I need to add configuration options the user can set from the NS Web UI?

> Please make sure to test both scenarios.

2018-07-31 17:15 UTC, gsanchietti commented
The fragment should be refactored to output multiple "PROXY" directives like:
```
PROXY <fqdn>; PROXY <green_ip>:3128
```
Also all code related to `phost` variable should be removed.

No need to add new options for the users, the generated file should be good for all environments.

2018-08-20 15:07 UTC, gsanchietti commented
Any news on this PR?

@ramiro can you implement the requested changes?

2018-08-20 16:17 UTC, ramiro commented
Yes, sorry for the delay. Will implement and test this this week.

2018-08-30 08:31 UTC, gsanchietti approved these changes
Everything seems good, thank you!

2018-08-30 08:31 UTC, merged