Fixed dashboard and filter pages
NethServer/nethserver-squid pull request #56
Opened 2020-05-29 15:50 UTC by andre8244

- Dashboard: fixed proxy status
- Filter: fixed UI when filter packages are not installed

https://github.com/NethServer/dev/issues/6185

2020-06-01 22:11 UTC, filippocarletti approved these changes

2020-06-03 07:08 UTC, gsanchietti requested changes

2020-06-03 07:08 UTC, gsanchietti commented on api/dashboard/read
> +    if (defined($av_dir_exists)) {
Suggestion, simpler to understand:
```
if (-d "/var/lib/squidclamav") {
    opendir(DIR, "/var/lib/squidclamav");
```
See also: https://perldoc.perl.org/functions/-X.html

2020-06-03 07:14 UTC, edospadoni approved these changes

2020-06-03 07:33 UTC, gsanchietti approved these changes

2020-06-03 07:36 UTC, merged